stages:
  clear_train:
    cmd: python3 scripts/clear_train.py data/train.csv
    deps:
    - data/train.csv
    - scripts/clear_train.py
    outs:
    - data/stage1
  data_preparation:
    cmd: python3 scripts/data_preparation.py data/stage1/train.csv
    deps:
    - data/stage1/train.csv
    - scripts/data_preparation.py
    outs:
    - data/stage2
  split_on_x_y:
    cmd: python3 scripts/split_on_x_y.py data/stage2/train.csv
    deps:
    - data/stage2/train.csv
    - scripts/split_on_x_y.py
    outs:
    - data/stage3
  split:
    cmd: python3 scripts/data_split.py data/stage3/train_x.csv data/stage3/train_y.csv
    deps:
    - data/stage3/train_x.csv
    - data/stage3/train_y.csv
    - scripts/data_split.py
    params:
    - split.split_ratio
    outs:
    - data/stage4
