stages:
  clear_train:
    cmd: python3 scripts/clear_train.py data/train.csv
    deps:
    - data/train.csv
    - scripts/clear_train.py
    outs:
    - data/stage1
  data_preparation:
    cmd: python3 scripts/data_preparation.py data/stage1/train.csv
    deps:
    - data/stage1/train.csv
    - scripts/data_preparation.py
    outs:
    - data/stage2
  split_on_x_y:
    cmd: python3 scripts/split_on_x_y.py data/stage2/train.csv
    deps:
    - data/stage2/train.csv
    - scripts/split_on_x_y.py
    outs:
    - data/stage3
